steps:
  # Paso 1: Construir la imagen de Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/cat-joyas-repo/app-image', '.']

  # Paso 2: Subir la imagen al Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/cat-joyas-repo/app-image']

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cat-joyas-repo/app-image'